theme: minima
title: Your awesome title
author: mangel119
email: miguel.sanabria@uao.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Getting ready to say Hello World!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
